### ISSUE TITLE
'QmMethod' has no attribute 'B3LYP_6_31G_D'

### ISSUE THREAD

**Issue by MKCarter** [valence-labs/OpenQDC#115]
Hi,

Thanks for sharing the code, it looks very interesting.

I have installed the repo using the following instructions:

```
git clone https://github.com/valence-labs/OpenQDC.git
cd OpenQDC
mamba env create -n openqdc -f env.yml
conda activate openqdc
pip install -e .
```

Everything installed fine, I then retried a couple of datasets using:

`openqdc download Spice QMugs`

This also worked fine. However, when running the tutorial, I run into an error when running the cell:

```
from openqdc.methods import QmMethod
    
# Get the b3lyp/6-31g* method
method = QmMethod.B3LYP_6_31G_D
method.atom_energies_dict
```

Which returns the following error:

```
AttributeError                            Traceback (most recent call last)
Cell In[24], line 4
      1 from openqdc.methods import QmMethod
      3 # Get the b3lyp[/6-31g](http://localhost:8888/6-31g)* method
----> 4 method = QmMethod.B3LYP_6_31G_D
      5 method.atom_energies_dict

AttributeError: type object 'QmMethod' has no attribute 'B3LYP_6_31G_D'
```

Do you have any suggestions on how to fix this?

Thanks,
Mike

**Comment by FNTwin** [comment]
Hi Mike,

`QmMethod` is the interface for the underlining level of theory methods that are further categorized under `PotentialMethod` and `InteractionMethod`. You want to call the `PotentialMethod` or `InteractionMethod` to access the attributes.

```python
from openqdc.methods import PotentialMethod
# Get the b3lyp/6-31g* method
method = PotentialMethod.B3LYP_6_31G_D
method.atom_energies_dict # return a dict of Hartree energies
```
